---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      run: whoami
  replicas: 1
  template:
    metadata:
      labels:
        run: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    run: whoami
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: "kong"
  rules:
    - host: whoami.192.168.1.100.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /whoami
            backend:
              service:
                name: whoami
                port:
                  number: 8080

    
        
